export const fakeDomains = [
  {
    id: 0,
    tld: '.com',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 0, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      // { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 1,
    tld: '.net',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 2,
    tld: '.org',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 3,
    tld: '.dev',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 4,
    tld: '.app',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 5,
    tld: '.inc',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 6,
    tld: '.website',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 7,
    tld: '.io',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 8,
    tld: '.co',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 9,
    tld: '.ai',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 10,
    tld: '.ca',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 11,
    tld: '.me',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 12,
    tld: '.de',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 13,
    tld: '.xyz',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 14,
    tld: '.club',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 15,
    tld: '.online',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 16,
    tld: '.info',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 17,
    tld: '.store',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 18,
    tld: '.best',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 19,
    tld: '.live',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 20,
    tld: '.tech',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 21,
    tld: '.pro',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 22,
    tld: '.world',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 23,
    tld: '.space',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 24,
    tld: '.vip',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 25,
    tld: '.life',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 26,
    tld: '.in',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 27,
    tld: '.is',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 28,
    tld: '.en',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
  {
    id: 29,
    tld: '.gg',
    root: undefined,
    ages: [
      { id: 0, age: 12, price: 34.99, discount: 20, isActive: true },
      { id: 1, age: 24, price: 69.99, discount: 30, isActive: false },
      { id: 2, age: 36, price: 104.99, discount: 40, isActive: false },
      { id: 3, age: 48, price: 139.99, discount: 50, isActive: false },
    ],
  },
];

// export const fakePlans = {
//   1: [
//     {
//       id: 1,
//       title: 'Basic',
//       monthly_price: 29.99,
//       discount: 0,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '10GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 2,
//       title: 'Standard',
//       monthly_price: 49.99,
//       discount: 10,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '20GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 3,
//       title: 'Business',
//       monthly_price: 79.99,
//       discount: 20,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '50GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 4,
//       title: 'Enterprise',
//       monthly_price: 149.99,
//       discount: 30,
//       isActive: true,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '100GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//   ],
//   12: [
//     {
//       id: 1,
//       title: 'Premium',
//       monthly_price: 199.5,
//       discount: 20,
//       isActive: false,
//       details: [
//         { id: 1, value: 'Host 5', field: 'Domain' },
//         { id: 2, value: '2GB NVMe', field: 'Storage' },
//         { id: 3, value: '50GB', field: 'Bandwidth' },
//         { id: 4, value: 'Free', field: 'SSL Certificate' },
//         { id: 5, value: '24/7', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 2,
//       title: 'Business',
//       monthly_price: 199.5,
//       discount: 70,
//       isActive: true,
//       details: [
//         { id: 1, value: 'Host 5', field: 'Domain' },
//         { id: 2, value: '2GB NVMe', field: 'Storage' },
//         { id: 3, value: '50GB', field: 'Bandwidth' },
//         { id: 4, value: 'Free', field: 'SSL Certificate' },
//         { id: 5, value: '24/7', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 3,
//       title: 'Online Store',
//       monthly_price: 199.5,
//       discount: 30,
//       isActive: false,
//       details: [
//         { id: 1, value: 'Host 5', field: 'Domain' },
//         { id: 2, value: '2GB NVMe', field: 'Storage' },
//         { id: 3, value: '50GB', field: 'Bandwidth' },
//         { id: 4, value: 'Free', field: 'SSL Certificate' },
//         { id: 5, value: '24/7', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 4,
//       title: 'Pro',
//       monthly_price: 199.5,
//       discount: 40,
//       isActive: false,
//       details: [
//         { id: 1, value: 'Host 5', field: 'Domain' },
//         { id: 2, value: '2GB NVMe', field: 'Storage' },
//         { id: 3, value: '50GB', field: 'Bandwidth' },
//         { id: 4, value: 'Free', field: 'SSL Certificate' },
//         { id: 5, value: '24/7', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//   ],
//   36: [
//     {
//       id: 1,
//       title: 'Basic',
//       monthly_price: 19.99,
//       discount: 0,
//       isActive: true,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '10GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 2,
//       title: 'Standard',
//       monthly_price: 39.99,
//       discount: 10,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '20GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 3,
//       title: 'Business',
//       monthly_price: 69.99,
//       discount: 20,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '50GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 4,
//       title: 'Enterprise',
//       monthly_price: 129.99,
//       discount: 30,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '100GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//   ],
//   48: [
//     {
//       id: 1,
//       title: 'Basic',
//       monthly_price: 17.99,
//       discount: 0,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '10GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 2,
//       title: 'Standard',
//       monthly_price: 37.99,
//       discount: 10,
//       isActive: true,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '20GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 3,
//       title: 'Business',
//       monthly_price: 65.99,
//       discount: 20,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '50GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//     {
//       id: 4,
//       title: 'Enterprise',
//       monthly_price: 119.99,
//       discount: 30,
//       isActive: false,
//       details: [
//         { id: 1, value: '1 Domain', field: 'Domain' },
//         { id: 2, value: '100GB SSD Storage', field: 'Storage' },
//         { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
//         { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
//         { id: 5, value: '24/7 Support', field: 'Support' },
//         { id: 6, value: '2GB NVMe', field: 'Storage' },
//         { id: 7, value: 'Free', field: 'SSL Certificate' },
//       ],
//     },
//   ],
// };

// Basic, Standart, Business, Enterprise, Pro, Online Store,
