const plans = {
  1: [
    {
      id: 1,
      title: 'Basic',
      monthly_price: 29.99,
      discount: 0,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '10GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Standard',
      monthly_price: 49.99,
      discount: 10,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '20GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Business',
      monthly_price: 79.99,
      discount: 20,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '50GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Enterprise',
      monthly_price: 149.99,
      discount: 30,
      isActive: true,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '100GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
  12: [
    {
      id: 1,
      title: 'Premium',
      monthly_price: 199.5,
      discount: 20,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Business',
      monthly_price: 199.5,
      discount: 70,
      isActive: true,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Online Store',
      monthly_price: 199.5,
      discount: 30,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Pro',
      monthly_price: 199.5,
      discount: 40,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
  36: [
    {
      id: 1,
      title: 'Basic',
      monthly_price: 19.99,
      discount: 0,
      isActive: true,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '10GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Standard',
      monthly_price: 39.99,
      discount: 10,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '20GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Business',
      monthly_price: 69.99,
      discount: 20,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '50GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Enterprise',
      monthly_price: 129.99,
      discount: 30,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '100GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
  48: [
    {
      id: 1,
      title: 'Basic',
      monthly_price: 17.99,
      discount: 0,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '10GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Standard',
      monthly_price: 37.99,
      discount: 10,
      isActive: true,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '20GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Business',
      monthly_price: 65.99,
      discount: 20,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '50GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Enterprise',
      monthly_price: 119.99,
      discount: 30,
      isActive: false,
      details: [
        { id: 1, value: '1 Domain', field: 'Domain' },
        { id: 2, value: '100GB SSD Storage', field: 'Storage' },
        { id: 3, value: 'Unlimited Bandwidth', field: 'Bandwidth' },
        { id: 4, value: 'Free SSL Certificate', field: 'SSL Certificate' },
        { id: 5, value: '24/7 Support', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
};

export const loadPlans = (months) => {
  return plans[months];
};
